<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\YandexBlocker.png" />
    <Resource Include="Assets\Fonts\Outfit.ttf" />
    <Resource Include="Assets\vpn.png" />
    <Resource Include="Assets\support.png" />
    <Resource Include="Assets\github.png" />
  </ItemGroup>

</Project>